version: "3.5"

services:
  web:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - dev

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27018:27018
    networks:
      - dev

networks:
  dev:
    name: dev
    driver: bridge